name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build version
      id: build_version
      run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Set up environment
      run: echo -e "REPSY_USERNAME=${{ secrets.REPSY_USERNAME }}\nREPSY_PASSWORD=${{ secrets.REPSY_PASSWORD }}" > ./secrets.properties

    - name: Publish
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: publish 

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: 'Create Lab ${{ steps.build_version.outputs.SOURCE_TAG }}'
        artifacts: './build/libs/createlab-${{ steps.build_version.outputs.SOURCE_TAG }}.jar'
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }}
